### ISSUE TITLE
Example code not running

### ISSUE THREAD

**Issue by wushukid** [aAbdz/CylShapeDecomposition#3]
Hi,
First of all thanks for sharing your work!
I am new to python, and I am trying to execute the code, but I keep getting KeyError=0.5 in many places along the code. 
I see that it's one of the outputs in some of the dictionaries (for example graph_v, rgraph_v), but I don't understand why am I getting this output rather than one which is accepted by the other dictionaries( graph_e,rgraph_e).
I would appreciate it if you could help me solve this problem.

Regards,
Daniel

**Comment by henkvanvoorst92** [comment]
Hi guys,
Similar to Daniel, this work looks very promising and seems something I could use very well. I have the same error as Daniel.
What I found is the following:

1) graph, graph_e, and graph_v in the functions rearrange graph and cyclic_graph are dictionaries
2) below how these dictionaries are created:
graph_e = {i: [i*2, i*2+1] for i in range(n_branch)}
graph_v = {i: i/2 for i in range(2*n_branch)}
3) keys for graph and graph_v range between 0 and n, keys of graph_e range between 0 and n/2. Values of graph_v range between 0 and n/2 with steps of 0.5
4) You call graph_e[graph_v[n]], thus you use the value of graph_v as key for graph_e 
5) in point 2 you see that by definition the values of the graph_v dictionary can be floats (half the values). It seems that this is the issue; you create values that are not in the keys of the graph_e dictionary.

I could not identify why this is done. Could you clarify this for us?

**Comment by aAbdz** [comment]
Hi,
Let me take a look at the code; I need to refresh my memory.

**Comment by aAbdz** [comment]
In earlier Python versions, "i/2" resulted in an integer. 
So, I changed "i/2" to "i//2", now written as graph_v = {i: i//2 for i in range(2*n_branch)}.
I corrected some of the deprecation issues as well; now it should run fine.
