### ISSUE TITLE
Results of code

### ISSUE THREAD

**Issue by wushukid** [aAbdz/CylShapeDecomposition#4]
Hi,

1.In the readme file, it says that there's supposed to be a results folder attached, but I cant' seem to find it. 
Can you please add it?

2. I am rather new in python so maybe I am just missing something, but how do I visualize the results? After running the code I have two list variables, but I don't actually know what to do with them.

Thank you very much.

**Comment by aAbdz** [comment]
Hi,
1) I added the "results" folder containing the decomposition results of the example object. 
2) As in the description, reconstruct both objects as voxel-based binary objects. 
3) To visualize the surface of a 3d binary image, either use Python or Matlab's isosurface. If you convert a voxel-based object into a mesh representation, then you can use MeshLab or many other tools developed for this purpose.
